on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            LOKI_PASSWORD
          vars: |
            DOMAIN
            DOMAIN_REDIRECT
            DOMAIN_GRAFANA
            DOMAIN_LOKI
            LOKI_USERNAME
        env:
          LOKI_PASSWORD: ${{ secrets.LOKI_PASSWORD }}
          DOMAIN: ${{ vars.DOMAIN }}
          DOMAIN_REDIRECT: ${{ vars.DOMAIN_REDIRECT }}
          DOMAIN_GRAFANA: ${{ vars.DOMAIN_GRAFANA }}
          DOMAIN_LOKI: ${{ vars.DOMAIN_LOKI }}
          LOKI_USERNAME: ${{ vars.LOKI_USERNAME }}
